version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI port
    networks:
      - inventory_network

  microservice1:
    build: ./microservice1
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - inventory_network

  microservice2:
    build: ./microservice2
    ports:
      - "8001:8001"
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - inventory_network

  http_server:
    build: ./http_server
    ports:
      - "8080:8080"
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - inventory_network

networks:
  inventory_network:
    driver: bridge
